### ISSUE TITLE
Using this image on GCE

### ISSUE THREAD

**Issue by yaronr** [cnf/docker-softether#5]
Hi

I've been using this image successfully on AWS.
Recently I've tried using it on GCE and failed (even with ip-forwarding enabled on the nodes).
It looks like only traffic on port 443 reaches softether, and everything else is blocked. I can connect with the Windows admin console just fine, but fail to connect using my Mac's VPN.

Any thoughts / ideas / experience around this?
Thanks.

**Comment by cnf** [comment]
None, I am afraid. Do you run it with --net=host, or -p every port?

**Comment by yaronr** [comment]
--net=host.
I thought it may be related to can-ip-forward, but even after enabling that, it doesn't seem to work..

**Comment by cnf** [comment]
Do the Softether logs say anything? maybe GCE blocks the ports you need (which seems likely, as one of them works and the others do not)

**Comment by cnf** [comment]
Closing, as there has been no feedback in over a year.
