### ISSUE TITLE
Needs --cap-add NET_ADMIN to command line (and need to pre-install iptables)

### ISSUE THREAD

**Issue by pocesar** [cnf/docker-softether#6]
Otherwise it won't be able to set iptables filters.

Plus it must install iptables (comes with none installed by default, had to `exec /bin/bash -c apt-get update && apt-get install iptables -y` for it to work properly)

**Comment by cnf** [comment]
Why do you need iptables in the container?

**Comment by pocesar** [comment]
when using Virtual NAT, Virtual DNS, Local Bridge, softether tries to set iptables rules, and fail

**Comment by cnf** [comment]
done.
